// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpoS0EbsdDhNfsjoE9_wWCVucE9VIoOc8',
    appId: '1:293433043221:web:25d55ae8fea6692dfca11c',
    messagingSenderId: '293433043221',
    projectId: 'yelb-ebfff',
    authDomain: 'yelb-ebfff.firebaseapp.com',
    storageBucket: 'yelb-ebfff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEwzdzpNzHYCxYQvEaV5wkvEVKERqC1is',
    appId: '1:293433043221:android:01f2f4b07c95048efca11c',
    messagingSenderId: '293433043221',
    projectId: 'yelb-ebfff',
    storageBucket: 'yelb-ebfff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgkTGWLJ97BHdsnF3IjeaJU82Y_Ak3mYU',
    appId: '1:293433043221:ios:fedff039e08ac249fca11c',
    messagingSenderId: '293433043221',
    projectId: 'yelb-ebfff',
    storageBucket: 'yelb-ebfff.appspot.com',
    iosBundleId: 'com.example.yelb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgkTGWLJ97BHdsnF3IjeaJU82Y_Ak3mYU',
    appId: '1:293433043221:ios:1fac70a9d5886d95fca11c',
    messagingSenderId: '293433043221',
    projectId: 'yelb-ebfff',
    storageBucket: 'yelb-ebfff.appspot.com',
    iosBundleId: 'com.example.yelb.RunnerTests',
  );
}
